# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rDmNb84YX0nPQrrNxDfMujdIu5ahcNms
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.optim as optim
import torch.utils.data
from torch.autograd import variable

# import data
movies =pd.read_csv('ml-1m/movies.dat',sep=': :',header=None,engine='python',encoding='latin-1')
users =pd.read_csv('ml-1m/users.dat',sep=': :',header=None,engine='python',encoding='latin-1')
ratings =pd.read_csv('ml-1m/ratings.dat',sep=': :',header=None,engine='python',encoding='latin-1')

# splitting data